package cybersec.deception.client.utils;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum MockarooDataType {
    ADDRESS_LINE_2("Address Line 2"),
    AIRPORT_CODE("Airport Code"),
    AIRPORT_CONTINENT("Airport Continent"),
    AIRPORT_COUNTRY_CODE("Airport Country Code"),
    AIRPORT_ELEVATION_FEET("Airport Elevation (Feet)"),
    AIRPORT_GPS_CODE("Airport GPS Code"),
    AIRPORT_LATITUDE("Airport Latitude"),
    AIRPORT_LONGITUDE("Airport Longitude"),
    AIRPORT_MUNICIPALITY("Airport Municipality"),
    AIRPORT_NAME("Airport Name"),
    AIRPORT_REGION_CODE("Airport Region Code"),
    ANIMAL_COMMON_NAME("Animal Common Name"),
    ANIMAL_SCIENTIFIC_NAME("Animal Scientific Name"),
    APP_BUNDLE_ID("App Bundle ID"),
    APP_NAME("App Name"),
    APP_VERSION("App Version"),
    AVATAR("Avatar"),
    BASE64_IMAGE_URL("Base64 Image URL"),
    BINOMIAL_DISTRIBUTION("Binomial Distribution"),
    BITCOIN_ADDRESS("Bitcoin Address"),
    BLANK("Blank"),
    BOOLEAN("Boolean"),
    BUZZWORD("Buzzword"),
    CAR_MAKE("Car Make"),
    CAR_MODEL("Car Model"),
    CAR_MODEL_YEAR("Car Model Year"),
    CAR_VIN("Car VIN"),
    CATCH_PHRASE("Catch Phrase"),
    CHARACTER_SEQUENCE("Character Sequence"),
    CITY("City"),
    COLOR("Color"),
    COMPANY_NAME("Company Name"),
    CONSTRUCTION_HEAVY_EQUIPMENT("Construction Heavy Equipment"),
    CONSTRUCTION_MATERIAL("Construction Material"),
    CONSTRUCTION_ROLE("Construction Role"),
    CONSTRUCTION_STANDARD_COST_CODE("Construction Standard Cost Code"),
    CONSTRUCTION_SUBCONTRACT_CATEGORY("Construction Subcontract Category"),
    CONSTRUCTION_TRADE("Construction Trade"),
    COUNTRY("Country"),
    COUNTRY_CODE("Country Code"),
    CREDIT_CARD_NUMBER("Credit Card #"),
    CREDIT_CARD_TYPE("Credit Card Type"),
    CURRENCY("Currency"),
    CURRENCY_CODE("Currency Code"),
    CUSTOM_LIST("Custom List"),
    DATASET_COLUMN("Dataset Column"),
    DATETIME("Datetime"),
    DEPARTMENT_CORPORATE("Department (Corporate)"),
    DEPARTMENT_RETAIL("Department (Retail)"),
    DIGIT_SEQUENCE("Digit Sequence"),
    DOMAIN_NAME("Domain Name"),
    DRUG_COMPANY("Drug Company"),
    DRUG_NAME_BRAND("Drug Name (Brand)"),
    DRUG_NAME_GENERIC("Drug Name (Generic)"),
    DUMMY_IMAGE_URL("Dummy Image URL"),
    DUNS_NUMBER("DUNS Number"),
    EIN("EIN"),
    EMAIL_ADDRESS("Email Address"),
    ENCRYPT("Encrypt"),
    ETHEREUM_ADDRESS("Ethereum Address"),
    EXPONENTIAL_DISTRIBUTION("Exponential Distribution"),
    FAKE_COMPANY_NAME("Fake Company Name"),
    FAMILY_NAME_CHINESE("Family Name (Chinese)"),
    FDA_NDC_CODE("FDA NDC Code"),
    FILE_NAME("File Name"),
    FIRST_NAME("First Name"),
    FIRST_NAME_EUROPEAN("First Name (European)"),
    FIRST_NAME_FEMALE("First Name (Female)"),
    FIRST_NAME_MALE("First Name (Male)"),
    FORMULA("Formula"),
    FREQUENCY("Frequency"),
    FULL_NAME("Full Name"),
    GENDER("Gender"),
    GENDER_ABBREV("Gender (abbrev)"),
    GENDER_BINARY("Gender (Binary)"),
    GENDER_FACEBOOK("Gender (Facebook)"),
    GEOMETRIC_DISTRIBUTION("Geometric Distribution"),
    GIVEN_NAME_CHINESE("Given Name (Chinese)"),
    GUID("GUID"),
    HEX_COLOR("Hex Color"),
    IBAN("IBAN"),
    ICD10_DIAGNOSIS_CODE("ICD10 Diagnosis Code"),
    ICD10_DX_DESC_LONG("ICD10 Dx Desc (Long)"),
    ICD10_DX_DESC_SHORT("ICD10 Dx Desc (Short)"),
    ICD10_PROC_DESC_LONG("ICD10 Proc Desc (Long)"),
    ICD10_PROC_DESC_SHORT("ICD10 Proc Desc (Short)"),
    ICD10_PROCEDURE_CODE("ICD10 Procedure Code"),
    ICD9_DIAGNOSIS_CODE("ICD9 Diagnosis Code"),
    ICD9_DX_DESC_LONG("ICD9 Dx Desc (Long)"),
    ICD9_DX_DESC_SHORT("ICD9 Dx Desc (Short)"),
    ICD9_PROC_DESC_LONG("ICD9 Proc Desc (Long)"),
    ICD9_PROC_DESC_SHORT("ICD9 Proc Desc (Short)"),
    ICD9_PROCEDURE_CODE("ICD9 Procedure Code"),
    IP_ADDRESS_V4("IP Address v4"),
    IP_ADDRESS_V4_CIDR("IP Address v4 CIDR"),
    IP_ADDRESS_V6("IP Address v6"),
    IP_ADDRESS_V6_CIDR("IP Address v6 CIDR"),
    ISBN("ISBN"),
    JOB_TITLE("Job Title"),
    JSON_ARRAY("JSON Array"),
    LANGUAGE("Language"),
    LAST_NAME("Last Name"),
    LATITUDE("Latitude"),
    LINKEDIN_SKILL("LinkedIn Skill"),
    LONGITUDE("Longitude"),
    MAC_ADDRESS("MAC Address"),
    MD5("MD5"),
    MEDICARE_BENEFICIARY_ID("Medicare Beneficiary ID"),
    MIME_TYPE("MIME Type"),
    MOBILE_DEVICE_BRAND("Mobile Device Brand"),
    MOBILE_DEVICE_MODEL("Mobile Device Model"),
    MOBILE_DEVICE_OS("Mobile Device OS"),
    MOBILE_DEVICE_RELEASE_DATE("Mobile Device Release Date"),
    MONEY("Money"),
    MONGODB_OBJECTID("MongoDB ObjectID"),
    MOVIE_GENRES("Movie Genres"),
    MOVIE_TITLE("Movie Title"),
    NATO_PHONETIC("Nato Phonetic"),
    NAUGHTY_STRING("Naughty String"),
    NHS_NUMBER("NHS Number"),
    NORMAL_DISTRIBUTION("Normal Distribution"),
    NUMBER("Number"),
    PARAGRAPHS("Paragraphs"),
    PASSWORD("Password"),
    PASSWORD_HASH("Password Hash"),
    PHONE("Phone"),
    PLANT_COMMON_NAME("Plant Common Name"),
    PLANT_FAMILY("Plant Family"),
    PLANT_SCIENTIFIC_NAME("Plant Scientific Name"),
    POISSON_DISTRIBUTION("Poisson Distribution"),
    POSTAL_CODE("Postal Code"),
    PRODUCT_GROCERY("Product (Grocery)"),
    RACE("Race"),
    REGULAR_EXPRESSION("Regular Expression"),
    REPEATING_ELEMENT("Repeating Element"),
    ROW_NUMBER("Row Number"),
    SCENARIO("Scenario"),
    SENTENCES("Sentences"),
    SEQUENCE("Sequence"),
    SHA1("SHA1"),
    SHA256("SHA256"),
    SHIRT_SIZE("Shirt Size"),
    SHORT_HEX_COLOR("Short Hex Color"),
    SLOGAN("Slogan"),
    SQL_EXPRESSION("SQL Expression"),
    SSN("SSN"),
    STATE("State"),
    STATE_ABBREV("State (abbrev)"),
    STOCK_INDUSTRY("Stock Industry"),
    STOCK_MARKET("Stock Market"),
    STOCK_MARKET_CAP("Stock Market Cap"),
    STOCK_NAME("Stock Name"),
    STOCK_SECTOR("Stock Sector"),
    STOCK_SYMBOL("Stock Symbol"),
    STREET_ADDRESS("Street Address"),
    STREET_NAME("Street Name"),
    STREET_NUMBER("Street Number"),
    STREET_SUFFIX("Street Suffix"),
    SUFFIX("Suffix"),
    TEMPLATE("Template"),
    TEZOS_ACCOUNT("Tezos Account"),
    TEZOS_BLOCK("Tezos Block"),
    TEZOS_CONTRACT("Tezos Contract"),
    TEZOS_OPERATION("Tezos Operation"),
    TEZOS_SIGNATURE("Tezos Signature"),
    TIME("Time"),
    TIME_ZONE("Time Zone"),
    TITLE("Title"),
    TOP_LEVEL_DOMAIN("Top Level Domain"),
    ULID("ULID"),
    UNIVERSITY("University"),
    URL("URL"),
    USER_AGENT("User Agent"),
    USERNAME("Username"),
    WORDS("Words");

    private final String displayName;

    MockarooDataType(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public static List<String> getAllDisplayNames() {
        return Arrays.stream(MockarooDataType.values())
                .map(MockarooDataType::getDisplayName)
                .collect(Collectors.toList());
    }
}
